# Generated by Django 4.0.2 on 2022-02-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='main_doctor_id',
            new_name='main_doctor',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='parent1_id',
            new_name='parent1',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='parent2_id',
            new_name='parent2',
        ),
        migrations.RenameField(
            model_name='rpps',
            old_name='rpps_id',
            new_name='rpps',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='treatment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trustedperson',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='trustedperson',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userdisease',
            old_name='disease_id',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='userdisease',
            old_name='user_id',
            new_name='user',
        ),
    ]
