# Generated by Django 4.0.2 on 2022-02-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0004_remove_trustedperson_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trustedperson',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='trustedperson',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
