# Generated by Django 4.0.2 on 2022-02-10 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0008_alter_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='main_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User_main_doctor', to='login_signup.doctor'),
        ),
    ]
