# Generated by Django 4.0.2 on 2022-02-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0014_alter_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MEDICAL_USER', 'Medical User'), ('PATIENT', 'Patient')], default='PATIENT', max_length=12, verbose_name='Rôle'),
        ),
    ]
