# Generated by Django 4.0.2 on 2022-02-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0015_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_use_medical_stuff', 'Can use medical stuff'),)},
        ),
    ]
