# Generated by Django 4.0.2 on 2022-02-15 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0017_alter_appointment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_signup.treatment'),
        ),
    ]
