# Generated by Django 4.0.2 on 2022-02-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0018_prescription_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diseases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_signup.diseases'),
        ),
    ]
