# Generated by Django 4.0.2 on 2022-02-17 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0019_prescription_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diseases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_signup.diseases', verbose_name='Maladie'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_signup.doctor', verbose_name='Médecin'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='is_permanent',
            field=models.BooleanField(default=False, verbose_name='Est-ce permanent'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.TextField(verbose_name='Informations complémentaire'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login_signup.treatment', verbose_name='Traitement'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
    ]
