# Generated by Django 4.0.2 on 2022-02-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0021_alter_prescription_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
