# Generated by Django 4.0.2 on 2022-02-17 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0022_prescription_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseases',
            name='cures',
        ),
        migrations.RemoveField(
            model_name='diseases',
            name='symptoms',
        ),
    ]
