# Generated by Django 4.0.2 on 2022-02-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0023_remove_diseases_cures_remove_diseases_symptoms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mail',
        ),
    ]
