# Generated by Django 4.0.2 on 2022-02-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0024_remove_customuser_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_scan',
            field=models.ImageField(blank=True, null=True, upload_to='prescription_scan'),
        ),
    ]
