# Generated by Django 4.0.2 on 2022-02-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0025_prescription_prescription_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
