# Generated by Django 4.0.2 on 2022-02-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0026_treatment_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdisease',
            old_name='isCurrent',
            new_name='is_active',
        ),
    ]
