# Generated by Django 4.0.2 on 2022-02-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0028_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_signup_progress',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
