# Generated by Django 4.0.2 on 2022-02-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0030_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messages',
            new_name='message',
        ),
    ]
