# Generated by Django 4.0.2 on 2022-02-23 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0032_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to=settings.AUTH_USER_MODEL),
        ),
    ]
