# Generated by Django 4.0.2 on 2022-02-23 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0033_message_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_user',
            field=models.ManyToManyField(null=True, related_name='blocked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
