# Generated by Django 4.0.2 on 2022-02-24 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0037_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='has_read',
            field=models.ManyToManyField(related_name='has_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
