# Generated by Django 4.0.2 on 2022-02-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0039_remove_message_has_read_message_has_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='has_read',
        ),
    ]
