# Generated by Django 4.0.2 on 2022-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0043_alter_notification_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
