# Generated by Django 4.0.2 on 2022-04-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0045_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='author',
            new_name='user',
        ),
    ]
