# Generated by Django 4.0.2 on 2022-04-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup', '0046_rename_author_news_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user',
            new_name='author',
        ),
    ]
