from login_signup.models.appointment import Appointment
from login_signup.models.doctor import Doctor
from login_signup.models.location import Location
from login_signup.models.prescription import Prescription
from login_signup.models.trustedUser import TrustedPerson
from login_signup.models.customUser import CustomUser
from login_signup.models.diseases import Diseases
from login_signup.models.treatment import Treatment
from login_signup.models.userDisease import UserDisease
from login_signup.models.job import Job
from login_signup.models.rpps import RPPS
from login_signup.models.message import Message
from login_signup.models.notification import Notification
from login_signup.models.news import News
